name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Copy CV document
        run: cp README.md content/html.md

      - name: Convert to PDF
        uses: docker://pandoc/ubuntu-latex:2.14.1
        with:
          args: -o static/mlbright-cv.pdf README.md

      - name: Build
        run: hugo --minify

      - name: Stop Jekyll from running
        run: touch public/.nojeckyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
